### ISSUE TITLE
Multiple transactions without exhausting connections

### ISSUE THREAD

**Issue by anderfjord** [lukequest/mariadb-transact#1]
What is the correct way to perform multiple transactions on a connection / pool of connections without exhausting sql connections? Should a TransactionManager be instantiated for each transaction, or should a single instance handle multiple transactions? If the latter, then is the right way to do it to first create and init the transaction manager, and then do a begin() for each separate transaction? If yes, then does a call to close() end the individual transaction or does it wipe out the manager instance?

In my case, I have a sql table set up as a queue, and am using mariadb-transact to perform transactions in which I select and delete a record from the queue. Pinging the queue for entries occurs on a period basis (1 second). The problem I'm running into is that the number of sql connections in use seems to grow with every transaction, despite always calling commit/rollback, and calling close() at the end. I have tried both creating a TransactionManager instance for each transaction, and also creating a single manager instance and running multiple transactions against it. Unfortunately, the problem persists.

Obviously I'm not doing something right, and so wanted to get a better idea as to what you'd consider proper practice in the case of multiple transactions. A basic example would be much appreciated. Thanks in advance.

**Comment by lukequest** [comment]
Wow, this is more than a year old. I'm so rarely on GitHub and didn't think anyone would actually use this library; I never thought to check if there were any issues until just now. I assume you moved on to something else long ago, so sorry for not answering on time.

To summarize, you were basically correct about creating and initializing the TransactionManager once, then calling begin() for each transaction. If the connection pool is exhausted because there are too many transactions going on, any further calls to begin() should be queued until a previous transaction completes. The number of SQL connections shouldn't grow beyond poolsize + 1, unless you call init() multiple times I guess.

If you're still interested at all, let me know and I'll try to help.
